apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: slag

resources:
  - namespace.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: slag
  app.kubernetes.io/part-of: slag

images:
  - name: ghcr.io/theoutdoorprogrammer/slag
    newTag: latest
